# Map specific models
models:
  default: models/human/model.sdf
  male: models/citizen_extras_male_03/model.sdf
  female: models/citizen_extras_female_02/model.sdf
  female_2: models/citizen_extras_female_03/model.sdf

# Triggers for Scenarios
triggers:
  frontal_approach_human:
    - action: spawn
      name: human
      model: male
      # Robot goes -3,-3 to 3,3. Human starts slightly closer at 2,2 to avoid goal occlusion
      pose: [2.0, 2.0, -2.35]
      path: [[2.0, 2.0], [-3.0, -3.0]]
      speed: 0.6

  intersection_human:
    - action: spawn
      name: human
      model: female
      # Robot goes -3,0 to 3,0 (X-axis). Human goes 0,-3 to 0,3 (Y-axis crossing)
      pose: [1.0, -3.0, 1.57] # Facing +Y
      path: [[1.0, -3.0], [1.0, 3.0]]
      speed: 0.7

  doorway_human:
    - action: spawn
      name: human
      model: female_2
      # Robot goes 1.5,0 to 1.5,7 (+Y). Human spawns slightly closer at 1.5,6
      pose: [1.5, 7.0, -1.57] # Facing -Y (towards robot)
      path: [[1.5, 7.0], [1.5, 0.0]]
      speed: 0.5
